_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "swin_base_patch4_window12_384.pkl"

SOLVER:
  IMS_PER_BATCH: 4  # batch size
  BASE_LR: 0.0001
  STEPS: (35200, 38400)
  MAX_ITER: 40000  # epoch: 100(bs=4)
  CHECKPOINT_PERIOD: 8000  # every 20 epoch(bs=4)
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
TEST:
  EVAL_PERIOD: 4000  # every 10 epoch(bs=4)

FINE_TUNING:
  ENABLE: False
  FREEZE_AT: 0  # General freezing stage, not used yet
  BACKBONE:
    NAME: "Swin"
  SWIN:
    PATCH_EMBED: True
    POS_DROP: True
    LAYERS: [0, 1, 2, 3]
    NORMS: ["norm0", "norm1", "norm2", "norm3"]
  SEM_SEG_HEAD:
    PIXEL_DECODER:
      ADAPTER: False
    PREDICTOR:
      ADAPTER: False

OUTPUT_DIR: "output/coco/maskformer2_swin_base_384_bs16_50ep"